function [ dirArray ] = getDirs(title)
%--------------------------------------------------------------------------
%
% getDirs.m:
%   Subfunction that propmts the user to select one or multiple #Ch1 and/or
%   #Ch2 project folders. 
%
% Description:
%   The function is mainly used in batch processing scripts, and allows the 
%   user to select multiple directories at once. It uses the sub-function 
%   uigetfile_n_dir.m [1].
%
% Syntax:  
%   [ dirArray ] = getDirs(title)
% 
% Inputs:
%   1. The function opens the file explorer and prompts the user to select 
%      one or multiple #Ch1 and/or #Ch2 project folders.
%   2. title - User-defined text that appears in the title bar of the input 
%      dialog box.
% 
% Outputs:
%   dirArray - 2D cell array containing the selected project folders #Ch1 
%              and #Ch2 in the first row and the corresponding path of the 
%              project folders in the 2nd row (see example below).  
% 
% Example: 
%   Cell array 'dirArray' of #Ch1 and #Ch2 project folders and their path 
%   as generated by the function getDirs.m
%   dirArray = {'#01Ch1',      '#01Ch2',      '#02Ch1',      '#02Ch2';
%               'path_#01Ch1', 'path_#01Ch2', 'path_#02Ch1', 'path_#02Ch2'}
% 
% Other m-files required: 
%   Subfunctions: uigetfile_n_dir.m
%  
% See also: 
%   scriptGetFretTraces.m
%
% References:
%   [1] uigetfile_n_dir.m is a BSD 3-clause licensed function. 
%   (Copyright (c) 2011, Peugas, all rights reserved)
%
% Authors: 
%   - P.G.
%
% Copyright:
%    2011-2020 Columbia Univiversity / RFMH All Rights Reserved.
%
% -------------------------------------------------------------------------


dirs = {};

switch nargin
    case 1
        start_path='';
        dialog_title=title;
    case 0
        start_path='';
        dialog_title='';
end

while 1
    % Get file name from user.
    f = uigetfile_n_dir(start_path,dialog_title);
    
    if iscell(f)
        dirs = [dirs f]; %#ok<AGROW>
    else
        break  %user hit cancel
    end
end

dirArray=cell(2,length(dirs));

for i=1:length(dirs)
    file=dirs{i};
    fileName=textscan(file,'%s %s %d %s','delimiter','#');
    dirName          = char(fileName{1});
    pathName         = ['#' char(fileName{2})];
    newPathName      = pathName(1:length(pathName)-1);
    basepath         = [dirName newPathName];
    noExp            = sprintf('%02d',fileName{3});
    
    if ~isempty(noExp)     
        dataSet      = ['#' noExp char(fileName{4})];
    else
        dataSet      = []; 
    end
    
    dirArray{1,i}    = dataSet;
    dirArray{2,i}    = basepath;
end

end

