%--------------------------------------------------------------------------
%
% scriptGetSegResults.m:
%   Batch processing script that runs the function getSegResults_2 on user
%   selected directories.
%
% Description:
%   The script reads the file results.mat (generated by 
%   'scriptGetSegTrackingAnalysis.m') and executes the function 
%   getSegResults_2. This subfunction compiles all track segments of a cell 
%   into a matrix called SegResultsFinal. It additionally performs a 
%   statistical analysis of the track segment population and saves the 
%   results to the variable SegStats. The varibales SegResultsFinal and 
%   SegStats will be saved in the current working folder. If multiple 
%   experiment folders are selected the script vertically concatenates the 
%   martix SegStats.mat from individual experiments and saves the final 
%   results in the additional file CombinedStats.mat located in the parent
%   folder of the last selected experiment folder.
% 
% Syntax:  
%   scriptGetSegResults.m
% 
% Inputs:
%   A GUI interface prompts the user to select a list of Ch1 and/or Ch2 
%   file directories. Each selected directory must contain the data file 
%   results.mat.          
% 
% Outputs:
%   1. SegResultsFinal.mat (see getSegResults_2) 
%   2. SegStats.mat (see getSegResults_2) 
%   3. CombinedStats.mat: array in which 'SegStats.mat' from multiple 
%   experiments is concatenated vertically (saved in the parent 
%   directory of the last selected Ch1 / Ch2 directories)         
% 
% Other m-files required: 
%   Subfunctions: getSegResults_2
% 
% See also: 
%   scriptGetSegTrackingAnalysis
%
% Author:
%   - Signe Mathiasen May 2018
%   - P.G. July 2018 Modified code to handle also empty structure variables
%     'results.mat'. The function 'getSegResults_2' is used instaead of the 
%     old version 'GetSegResults'  
%
% Copyright:
%    2011-2020 Columbia Univiversity / RFMH All Rights Reserved.
%
% -------------------------------------------------------------------------
%% Combine the structure variable results.mat from different experiments
%  Use only Directories that conatin files results.mat 

clear;
dir=getDirs('Highlight and Open ACCEPTOR (#Ch1) Folders (HIT CANCEL TO END SELECTION)'); 
folders=numel(dir(1,:));
CombinedStats=[];

h = waitbar(0,'Processing Data...');

for n=1:folders %loop running over all folders

    try
        
        fn=[dir{2,n} filesep dir{1,n} filesep 'results.mat']; 

        %loading results.mat
        load(fn);
        
        [segResultsFinal,segStats] = getSegResults_2(results);
   
        filename=[dir{2,n} filesep dir{1,n} filesep 'SegResultsFinal.mat' ];
        save(filename,'segResultsFinal');
    
        filename=[dir{2,n} filesep dir{1,n} filesep 'SegStats.mat' ];
        save(filename,'segStats');
        
        CombinedStats = [CombinedStats;segStats]; %#ok<AGROW>
    
    catch
        warning(['no file results.mat in folder ' dir{1,n}]);
        continue
    end
    
    % Show Waitbar
    waitbar(n / folders)
    
end

close(h) 

%% Save CombinedStats in the last selected Folder

path    = dir{2,folders};
filename = [path filesep 'CombinedStats.mat'];
save(filename,'CombinedStats');

disp('finished...');

%% End


