#! /bin/bash
# This script automatically appends the copyright line and the GPL copying # statement at the end of the M-file Header. If there is no header, it 
# appends the copyright line and copying statement at the end of the file

# Strings - should be changed as a function of the version
year=`date +%Y`
licensefile="CopyingStatement"
packagename=$1
institution=${2:-"Danuser Lab - UTSouthwestern"}

echo "Adding GPL license for ${packagename}"

# Generate the Matlab copying statement
sed "s/Foobar/${packagename}/g" $licensefile | awk 'BEGIN{printf "%%\n%% Copyright (C) '$year', '"${institution}"' \n%%\n";} {printf "%% "; print}' > MatlabCopyingStatement

# Loop over all Matlab files in the repertory
# Note: ls does not handle space in filenames
for file in `ls *.m`
do
	#Find the last line of the header
	headerlastline=`awk '
	{if ($1 ~ /^%/) 
		{header=1;}
	else 
		{if (header == 1) 
			{nr=NR-1;exit 1};
		}
	};
	END{if(nr) print nr; else print NR}'  $file`

	# For debugging
	#echo $headerlastline

	# Insert the copying statement at the bottom of the header
	sed ''$headerlastline' r MatlabCopyingStatement' < $file > temp
	mv temp $file
done

for file in `ls ./*/*.m`
do
	#Find the last line of the header
	headerlastline=`awk '
	{if ($1 ~ /^%/) 
		{header=1;}
	else 
		{if (header == 1) 
			{nr=NR-1;exit 1};
		}
	};
	END{if(nr) print nr; else print NR}'  $file`

	# For debugging
	#echo $headerlastline

	# Insert the copying statement at the bottom of the header
	sed ''$headerlastline' r MatlabCopyingStatement' < $file > temp
	mv temp $file
done

# Remove temporary copying statement
rm MatlabCopyingStatement